pring:
  application:
    name: ${springboot.app.name:eurekaservice}

server:
  port: 8761

eureka:
  instance:
    hostname: ${springboot.app.name:eurekaservice}
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${server.port}/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF