version: '3'
services:

  eurekaservice:
    build: ./eureka
    ports:
      - "8761:8761"
    tty: true



  adsservice:
    build: ./ads
    ports:
      - "8088:8088"
    tty: true
    environment:
      - REGISTRY_HOST=eurekaservice

    depends_on:
      - eurekaservice

  maintenanceservice:
    build: ./maintenance
    ports:
      - "8086:8086"
    environment:
      - REGISTRY_HOST=eurekaservice
    tty: true
    depends_on:
      - eurekaservice

  orderservice:
    build: ./ordering
    ports:
      - "8089:8089"
    environment:
      - REGISTRY_HOST=eurekaservice
    tty: true
    depends_on:
      - eurekaservice

  searchsevice:
    build: ./search
    ports:
      - "8091:8091"
    environment:
      - REGISTRY_HOST=eurekaservice
    tty: true
    depends_on:
      - eurekaservice

  messageservice:
    build: ./messages
    ports:
      - "8084:8084"
    environment:
      - REGISTRY_HOST=eurekaservice
    tty: true
    depends_on:
      - eurekaservice

  authservice:
    build: ./authentication
    ports:
      - "8443:8443"
    environment:
      - REGISTRY_HOST=eurekaservice
    tty: true
    depends_on:
      - eurekaservice

  paymentservice:
    build: ./payment
    ports:
      - "8090:8090"
    environment:
      - REGISTRY_HOST=eurekaservice
    tty: true
    depends_on:
      - eurekaservice






