version: '3'
services:

  eurekaservice:
    build: ./eureka
    ports:
      - "8761:8761"
    tty: true



  adsservice:
    build: ./ads
    ports:
      - "8098:8098"
    tty: true
    environment:
      - REGISTRY_HOST=eurekaservice
      - MYSQL_HOST=users-database

    depends_on:
      - users-database
      - eurekaservice

  maintenanceservice:
    build: ./maintenance
    ports:
      - "8086:8086"
    environment:
      - REGISTRY_HOST=eurekaservice
      - MYSQL_HOST=users-database

    tty: true
    depends_on:
      - users-database
      - eurekaservice
#
  orderservice:
    build: ./ordering
    ports:
      - "8089:8089"
    environment:
      - REGISTRY_HOST=eurekaservice
      - MYSQL_HOST=users-database
    tty: true
    depends_on:
      - users-database
      - eurekaservice

#  searchsevice:
#    build: ./search
#    ports:
#      - "8091:8091"
#    environment:
#      - REGISTRY_HOST=eurekaservice
#    tty: true
#    depends_on:
#      - eurekaservice
#
#  messageservice:
#    build: ./messages
#    ports:
#      - "8084:8084"
#    environment:
#      - REGISTRY_HOST=eurekaservice
#      -  MYSQL_HOST=users-database
#    tty: true
#    depends_on:
#      - eurekaservice
#      - users-database
#
#  authservice:
#    build: ./authentication
#    ports:
#      - "8443:8443"
#    environment:
#      - REGISTRY_HOST=eurekaservice
#    tty: true
#    depends_on:
#      - eurekaservice
#
  paymentservice:
    build: ./payment
    ports:
      - "8090:8090"
    environment:
      - REGISTRY_HOST=eurekaservice
      - MYSQL_HOST=users-database
    tty: true
    depends_on:
      - eurekaservice
      - users-database

  zuul:
    build: ./zuul
    ports:
      - "8662:8662"
    environment:
      REGISTRY_HOST: eurekaservice
    tty: true
    depends_on:
      - eurekaservice
      - adsservice
#      - authservice
      - maintenanceservice
#      - orderservice
      - paymentservice
#      - searchsevice

  users-database:
    image: mariadb:10.2
    container_name: users-database
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: services
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - usersdata:/var/lib/mysql


volumes:
  #  mysqldata:
  usersdata:


